Add fzf popup

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -170,7 +170,7 @@ function gretting_message() {
 
 # Open project under workspace folder
 function workspace_fzf() {
-  cd $WORKSPACE; ls -d */ | fzf | { cd -; read result; cd $WORKSPACE/$result }
+  cd $WORKSPACE; ls -d */ | fzfp | { cd -; read result; cd $WORKSPACE/$result }
   zle && zle reset-prompt
 }
 
@@ -184,7 +184,7 @@ function open_app_fzf() {
 # First param take local path to set of commands, i.e. ~/local/cmds
 function run_cmds_fzf() {
   echo $1
-  local cmd=$(cat $1 | fzf)
+  local cmd=$(cat $1 | ${2-"fzfp"})
   if [ -n "$cmd" ]; then
     local escape=$(echo $cmd | sed 's/[]\/$*.^[]/\\&/g')
     echo -e "$cmd\n$(cat $1 | sed "s/$escape//g" | sed '/^$/d')" > $1
@@ -262,6 +262,74 @@ function pass_fzf() {
   fi
 
   pass show "$passfile" --clip || return
+}
+
+function fzfp() {
+  fail() {
+      echo "$1" >&2
+      exit 2
+  }
+
+  fzf=$(command -v fzf 2>/dev/null) || fzf=$(dirname $0)/fzf
+  [[ -x "$fzf" ]] || fail 'fzf executable not found'
+
+  if [[ -n $TMUX_POPUP_NESTED_FB ]]; then
+      eval "$TMUX_POPUP_NESTED_FB" && exec fzf "$@"
+  fi
+
+  args=('--no-height')
+  while (($#)); do
+      arg=$1
+      case $arg in
+      --height | --width)
+          eval "${arg:2}=$2"
+          shift
+          ;;
+      --height=* | --width=*)
+          eval "${arg:2}"
+          ;;
+      *)
+          args+=("$arg")
+          ;;
+      esac
+      shift
+  done
+
+  opts=$(printf '%q ' "${args[@]}")
+
+  [[ -z $height ]] && height=${TMUX_POPUP_HEIGHT:-80%}
+  [[ -z $width ]] && width=${TMUX_POPUP_WIDTH:-80%}
+
+  envs="SHELL=$SHELL"
+  [[ -n $FZF_DEFAULT_OPTS ]] && envs="$envs FZF_DEFAULT_OPTS=$(printf %q "$FZF_DEFAULT_OPTS")"
+  [[ -n $FZF_DEFAULT_COMMAND ]] && envs="$envs FZF_DEFAULT_COMMAND=$(printf %q "$FZF_DEFAULT_COMMAND")"
+
+  id=$RANDOM
+  cmd_file="${TMPDIR:-/tmp}/fzf-cmd-file-$id"
+  pstdin="${TMPDIR:-/tmp}/fzf-pstdin-$id"
+  pstdout="${TMPDIR:-/tmp}/fzf-pstdout-$id"
+
+  clean_cmd="command rm -f $cmd_file $pstdin $pstdout"
+
+  cleanup() {
+      eval "$clean_cmd"
+  }
+  trap 'cleanup' EXIT
+
+  mkfifo "$pstdout"
+
+  echo -n "trap '$clean_cmd' EXIT SIGINT SIGTERM SIGHUP;" >"$cmd_file"
+
+  if [[ -t 0 ]]; then
+      echo -n "$fzf $opts > $pstdout" >>"$cmd_file"
+  else
+      mkfifo "$pstdin"
+      echo -n "$fzf $opts < $pstdin > $pstdout" >>"$cmd_file"
+      cat <&0 >"$pstdin" &
+  fi
+  cat "$pstdout" &
+
+  tmux popup -d '#{pane_current_path}' -xC -yC -w$width -h$height -E "$envs zsh $cmd_file"
 }
 
 autoload -z edit-command-line
